// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // CLI (migrate/introspection) går via session pooler (5432) — transaction
    // pooler (6543) klarar inte migrationer. Runtime använder DATABASE_URL
    // via @prisma/adapter-pg i lib/db/client.ts.
    url: process.env["DIRECT_URL"],
  },
});
